version: "3.9"
name: bootapi

services:
  db:
    container_name: db
    image: postgres
    restart: always
    build:
      dockerfile: db/Dockerfile
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/
      - ./db/scripts/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  api:
    container_name: api
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
      extra_hosts:
        - "host.docker.internal:host-gateway"
    ports:
      - "8080:8080"
    links:
      - db